### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by avitex**
Feel free to disregard, just some changes.

- Add feature doc in docs.rs
- Remove builders and associated deps for it (my personal opinion, I would rather create the struct with defaults and set the fields I care about)
- Rename the feature (another personal preference).

### CODE REVIEW

**Comment by avitex** [comment]
On another note, is System.service used for anything?

**Comment by MOZGIII** [comment]
Thanks for suggestions, and good point about the System.service - I lost it, but it gors into the second argument of getaddrinfo.
I'll take a deeper look into the code in a bit.

**Comment by MOZGIII** [comment]
Hey, I did look into the proposed changes, and here are my thoughts:

> * Add feature doc in docs.rs

Not sure why it is useful. Can you explain more why is this necessary?

> * Remove builders and associated deps for it (my personal opinion, I would rather create the struct with defaults and set the fields I care about)

It's my preference as well, but to respect people that want/need builders I decided to provide both builder and direct construction patterns. It is still relevant I think, so I'll keep the builders.
The `derivative`, however, was only used to provide a single, simple default value, and that one I'll cut to improve the compile times.

> * Rename the feature (another personal preference).

I like this, and I'd be happy to cherry-pick it.

**Comment by MOZGIII** [comment]
I've pulled most of the changes manually, so I'm going to close the PR for now. Feel free to continue the discussion here though - I'm still curious about the doc feature.

**Pull request closed without merging**
